[sncast.devnet]
account = "devnet_deployer"
url = "http://localhost:5050"

[sncast.devnet.accounts.devnet_deployer]
address = "0x064b48806902a367c8598f4f95c305e8c1a1acba5f082d294a43793113115691"
private_key = "0x71d7bb07b9a64f6f78ac4c816aff4da9"
public_key = "0x039d9e6ce352ad4530a0ef5d5a18fd3303c3606a7fa6ac5b620020ad681cc33b"
type = "open_zeppelin"

[sncast.sepolia]
account = "sepolia_deployer"
url = "https://starknet-sepolia.g.alchemy.com/starknet/version/rpc/v0_10/GUBwFqKhSgn4mwVbN6Sbn"

[sncast.sepolia.accounts.sepolia_deployer]
address = "0x0759a4374389b0e3cfcc59d49310b6bc75bb12bbf8ce550eb5c2f026918bb344"
private_key = "0x0154de503c7553e078b28044f15b60323899d9437bd44e99d9ab629acbada47a"
public_key = "0x05ae8b012236dcc418e61fc86706f1b5c3c3c53eb379b2edbdbfcf306d1cb1ee"
type = "open_zeppelin"
